spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false # Для отладки
  config:

    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5000/bank_db
    username: bank_user
    password: bank_pass

  liquibase:
    change-log: classpath:db/migration/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration: 900000
  refresh-token:
    expiration: 2592000000

app:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}

encryption:
  key: ${ENCRYPTION_KEY}
springdoc:
  swagger-ui:
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    org:
      springframework:
        web: TRACE
      thymeleaf: TRACE
server:
  port: 8081